# Generated by Django 3.0.5 on 2020-04-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('estatus', models.BooleanField(default=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('edicion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creacion'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('contrasenia', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('imagen', models.ImageField(blank=True, default='perfil.jpg', null=True, upload_to='clientes')),
                ('estatus', models.BooleanField(default=True, verbose_name='activo')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('edicion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('contrasenia', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('imagen', models.ImageField(blank=True, default='perfil.jpg', null=True, upload_to='usuarios')),
                ('perfil', models.BooleanField(default=False)),
                ('estatus', models.BooleanField(default=True, verbose_name='Activo')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('edicion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creacion'],
            },
        ),
    ]
