# Generated by Django 3.0.5 on 2020-05-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20200503_2334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
