# Generated by Django 3.0.5 on 2020-05-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0007_auto_20200518_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nuevo'), (1, 'Usado')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Producto'), (1, 'Servicio'), (2, 'Medicina')]),
        ),
    ]
